### PR TITLE
admin api get app

### PR DESCRIPTION
**Pull request by Setheck**
While digging through the userbase code I discovered this undocumented api and thought others might be interested in it as well.

* Document `Get App` api

### CODE REVIEW

**Comment by Setheck** [comment]
I discovered the Get App api, when trying to figure out how I can list users without logging into the web ui. Since trying out seemed to work just fine, I thought I would help out by sending over a pr.
I'm not sure how you want to handle the sub objects eg `users.username`. 
But i'm sure this will help others. I tried to follow existing style and I'm happy to iterate.

**Comment by j-berman** [comment]
Thank you for this!! Cool to see someone digging through the codebase and submit a PR like this. 

We haven't officially released this feature yet since we have a couple more tweaks in the works (it's the thing we're working on currently). The documentation may change slightly as a result, but appreciate this starting point!

**Comment by Setheck** [comment]
> Thank you for this!! Cool to see someone digging through the codebase and submit a PR like this.
> 
> We haven't officially released this feature yet since we have a couple more tweaks in the works (it's the thing we're working on currently). The documentation may change slightly as a result, but appreciate this starting point!
> 
> Edit: more clearly, let's leave this open for now until we get the feature done, then decide on how best to move forward.

Sounds Great, I imagine pagination needs to fit in there somewhere. 
In exploring userbase my main issue was that I there was no api access to users, which is why I started digging. I'm afraid I have to park using userbase for now in my project because of this. I understand it's still early days, and I'm looking forward to seeing how it evolves.

**Comment by j-berman** [comment]
Will get the changes shipped asap.

Until then, in case this is helpful, you could use the beta version of the Admin API, which is up and running. You'll first need to generate an access token in the [Userbase admin panel](https://v1.userbase.com/#edit-account) as shown [here](https://user-images.githubusercontent.com/26468430/75427933-3ad10080-58fc-11ea-9bca-c1435fd5d697.gif). There are 3 total endpoints you could currently use following the specs described in these PR's:

[UpdateUser & GetUser](https://github.com/encrypted-dev/userbase/pull/119)
[GetApp](https://github.com/encrypted-dev/userbase/pull/122)

The only change we're working on is that GetApp will actually just paginate users server-side, no need to worry about the pagination token.

We're also adding a new endpoint VerifyAuthToken. You'll be able to call that endpoint to verify that a user is presenting you a valid auth token. For example, a user logs into your web app, then calls a cloud function from within the app, and you want to ensure the user is logged into the web app from your cloud function.

The plan is to release all 4 endpoints as part of a larger release with complete documentation explaining the access token and each endpoint individually.

**Comment by j-berman** [comment]
@Setheck only a little late, but documentation is now updated with all relevant information as of #14 . We got distracted working on another feature, sorry for the delay :/

**Pull request closed without merging**
